import "./globals.css";
import "./index.css";

import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Webkit - WapBorhan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Toaster position="top-right" reverseOrder={false} />
        <div className="w-full max-w-[1615px] mx-auto">{children}</div>
      </body>
    </html>
  );
}
